[versions]
agp = "8.5.2"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"

composeBom = "2024.06.00"
activityCompose = "1.9.2"
lifecycle = "2.8.4"

room = "2.6.1"
coroutines = "1.8.1"

sqlcipher = "4.5.4"
sqlite = "2.4.0"
accompanistPermissions = "0.36.0"

junit = "4.13.2"
androidxJunit = "1.2.1"
espresso = "3.6.1"

material = "1.12.0"  # Material Components library
camerax = "1.3.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
# Compose (BOM)
compose-bom                  = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui                   = { module = "androidx.compose.ui:ui" }
compose-material3            = { module = "androidx.compose.material3:material3" }
compose-ui-tooling-preview   = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-tooling           = { module = "androidx.compose.ui:ui-tooling" }

androidx-activity-compose    = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

room-runtime   = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx       = { module = "androidx.room:room-ktx",     version.ref = "room" }
room-compiler  = { module = "androidx.room:room-compiler",version.ref = "room" }

sqlcipher      = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }

# tests
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core  = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

material-android = { module = "com.google.android.material:material", version.ref = "material" }

camerax-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camerax-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }